### ISSUE TITLE
Can't install look dependant to arc-icon as for regolith-llok-ayu-mirage

### ISSUE THREAD

**Issue by Pasqat** [regolith-linux/regolith-styles#46] opened 2021-07-18 10:15 UTC
I've a fresh install of Regolith and I'm trying to install other looks.
Whenever I try to install looks that use arc icons I get this error

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-look-ayu-mirage : Depends: arc-icon-theme but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kgilmer** [comment] 2021-07-18 15:43
Hi @Pasqat thanks for the bug report.  Looks like you found a 0-index issue in a package deployment script.  The problem should be resolved within an hour or two depending on the current package build load in launchpad.net.

**Closed as completed by kgilmer** 2021-07-18 15:43 UTC

**Comment by henningninneh** [comment] 2021-11-16 08:47
I'm facing the same issue with regolith 1.6 (I think) mobile desktop:
```

 $ sudo apt list --installed | grep regolith

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-compositor-picom-glx/impish,now 1.1.3-1 amd64 [installed,automatic]
regolith-default-settings/impish,now 1.0.8-1hirsute amd64 [installed,automatic]
regolith-desktop-mobile/impish,now 2.124-1hirsute amd64 [installed]
regolith-ftue/impish,now 1.1.2-1 amd64 [installed,automatic]
regolith-gnome-flashback/impish,now 2.6.2-1 amd64 [installed,automatic]
regolith-i3-gaps-config/impish,now 2.8.6-1 amd64 [installed,automatic]
regolith-i3xrocks-config/impish,now 3.6.4-1 amd64 [installed,automatic]
regolith-look-lascaille/impish,now 2.9.7-1 amd64 [installed,automatic]
regolith-rofi-config/impish,now 1.3.1-1 amd64 [installed,automatic]
regolith-rofication/impish,now 1.3.3-1 amd64 [installed,automatic]
regolith-styles/impish,now 2.9.7-1 amd64 [installed,automatic]
regolith-unclutter-xfixes/impish,now 1.5-2 amd64 [installed,automatic]
rofi/impish,now 1.6.1-1regolith1 amd64 [installed,automatic]

$ sudo apt-get install regolith-look-solarized-dark
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-look-solarized-dark : Depends: arc-icon-theme but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kgilmer** [comment] 2021-11-18 01:38
Hi @henningninneh , I am not able to reproduce this error.  What Regolith repository do you have setup?  `apt-cache policy | grep regolith`

**Comment by henningninneh** [comment] 2021-11-18 09:16
Hi @kgilmer, I'm on Ubuntu 21.10 impish, and my repository seems to be ppa.launchpad.net

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

$ apt-cache policy | grep regolith
 500 http://ppa.launchpad.net/regolith-linux/release/ubuntu impish/main i386 Packages
     release v=21.10,o=LP-PPA-regolith-linux-release,a=impish,n=impish,l=Regolith Linux - Release,c=main,b=i386
 500 http://ppa.launchpad.net/regolith-linux/release/ubuntu impish/main amd64 Packages
     release v=21.10,o=LP-PPA-regolith-linux-release,a=impish,n=impish,l=Regolith Linux - Release,c=main,b=amd64
```

**Comment by kgilmer** [comment] 2021-11-20 02:02
Ah, got it.  Should be fixed now @henningninneh :+1:

**Comment by henningninneh** [comment] 2021-11-20 10:55
It works! Thanks a lot!
